FinanceTracker/Controllers/FinanceManagerController.cs
using FinanceTracker.Models;
using FinanceTracker.Services;
using FinanceTracker.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;

namespace FinanceTracker.Controllers
{
    [Authorize(Roles ="admin,user")]
    public class FinanceManagerController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        private readonly UserService _userService;
      
        public FinanceManagerController(ApplicationDbContext dbContext, UserService userService)
        {

            _dbContext = dbContext;
            _userService = userService; 
        }
        
        public IActionResult Index()
        {

            int? customerId = _userService.fetchUser();
            if (customerId == null )
            {

                return View();
            }
            // the user is logged into the app 
            else
            {
                

                var transactions = _dbContext.Transactions.Where(e => e.CustomerId == customerId)
                                            .OrderByDescending(e => e.TimeStamp)
                                            .Include(e=>e.Category)
                                            .Select(e=>new TransactionViewModel()
                                            {
                                                TimeStamp = e.TimeStamp,
                                                Amount = e.amount,
                                                Description = e.description,
                                                Id = e.TransactionId,
                                                Type = e.Category.type.ToString(),
                                                Category = e.Category.Name,
                                               

                                            }).ToList();

               

                FinanceTrackerIndexViewModel indexViewModel = new FinanceTrackerIndexViewModel()
                {
                   
                   
                    transactionListItems = transactions


                };
                
                return View(indexViewModel);

            }
        }
        [HttpPost]
        public IActionResult FetchEditForm([FromBody] string transactionId)
        {
            
            var options = _dbContext.Categories.Select(e => new SelectListItem()
            {
                Value = e.CategoryId.ToString(),
                Text = e.Name
            });

            List<SelectListItem> OptionList = options.ToList();


            int transactionIdNumber = int.Parse(transactionId);

            var transaction = _dbContext.Transactions.Find(transactionIdNumber);


            TransactionEditFormViewModel editForm = new TransactionEditFormViewModel()
            {
                selectListItems = OptionList,
                TimeStamp = transaction.TimeStamp,
                amount = transaction.amount,
                description = transaction.description,
                CategoryId = transaction.CategoryId,
                TransactionId = transactionIdNumber
                



            };
            return PartialView(editForm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TransactionEditFormViewModel EditForm)
        {

            if (!ModelState.IsValid)
            {
                var message = "Invalid form, please check the your input";
                if (ModelState.TryGetValue("amount", out var amount) && amount.Errors.Any())
                {
                    message = "The amount and category type are not matching.";
                }
                // Constructing an object with the error message

                var errorObject = new { error = "Invalid form", message = message };

                return Json(errorObject);
            }
            else
            {
                var entityToUpdate = _dbContext.Transactions.Find(EditForm.TransactionId);

                if(entityToUpdate != null)
                {

                entityToUpdate.amount = EditForm.amount;
                entityToUpdate.description = EditForm.description;
                entityToUpdate.CategoryId = EditForm.CategoryId;
                entityToUpdate.TimeStamp = EditForm.TimeStamp;

                    _dbContext.SaveChanges();
                    var successObject = new { success = true };
                    return Json(successObject);
                }
                else
                {
                    // Constructing an object with the error message
                    var errorObject = new { error = "Transaction not found", message = "Transaction is not found" };

                    // Returning the error object as JSON
                    return Json(errorObject);
                }

            
            }

            
        }


        public IActionResult Create() {
            var options = _dbContext.Categories.Select(e => new SelectListItem()
            {
                Value = e.CategoryId.ToString(),
                Text = e.Name
            });

            List<SelectListItem> OptionList = options.ToList();

            var createForm = new TransactionCreateFormViewModel()
            {
                selectListItems = OptionList
            };
            return PartialView(createForm); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TransactionCreateFormViewModel createForm)
        {
            int? customerId =  _userService.fetchUser();
            if (!ModelState.IsValid)
            {
                var message = "Invalid form, please check the your input";
                if(ModelState.TryGetValue("amount",out var amount) && amount.Errors.Any())
                {
                    message = "The amount and category type are not matching.";
                }
                // Constructing an object with the error message
                
                var errorObject = new { error = "Invalid form",message = message };

                return Json(errorObject);
             



            }
            else
            {
                if (customerId == null)
                {
                    // Constructing an object with the error message
                    var errorObject = new { error = "User not found", message= "CustomerId is missing, make sure you have logged in" };

                    // Returning the error object as JSON
                    return Json(errorObject);
                }
                //add the new entity into the db 
                else
                {

                _dbContext.Add(new Transaction()
                {
                    TimeStamp = createForm.TimeStamp,
                    amount = createForm.amount,
                    description = createForm.description ?? string.Empty,
                    CategoryId = createForm.CategoryId,
                    CustomerId = (int)customerId,


                });
                _dbContext.SaveChanges();
                    var successObject = new {success = true };
                return Json(successObject);
                }
            }
        }

        [HttpPost]
        public IActionResult Delete([FromBody] string transactionId)
        {
            var id = int.Parse(transactionId);
            var transactionToDelete = _dbContext.Transactions.Find(id);
            if (transactionToDelete != null)
            {
                _dbContext.Transactions.Remove(transactionToDelete);
                _dbContext.SaveChanges();
                return Ok(new { status = 200, message = "Transaction deleted successfully", success = true });
            }
            else
            {
                // Constructing an object with the error message
                var errorObject = new { status = 404, message = "Transaction not found", error = true };

                // Returning the error object as JSON
                return NotFound(errorObject);
            }
        }

        public IActionResult Error(string error)
        {
            ViewData["error"] = error;
            return View();
        }
    }
        

        
}

FinanceTracker/Controllers/LoginController.cs
using FinanceTracker.Models;
using FinanceTracker.Utils;
using FinanceTracker.ViewModel;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace FinanceTracker.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public LoginController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(loginViewModel);
            }
            else
            {
                Customer? customer = Auth.IdentityValidation(loginViewModel, _dbContext);

                if (customer == null)
                {
                    return View(loginViewModel);
                }
                else
                {


                    if (Auth.Login(loginViewModel.password, customer, this.HttpContext).Result)
                    {

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        // Constructing an object with the error message
                        var errorObject = new { error = "Invalid form" };

                        // Returning the error object as JSON
                        return View(loginViewModel);
                    }



                }


            }

        }

        public IActionResult Logout()
        {
            if (User.Identity.IsAuthenticated)
            {

                HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Register()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterViewModel registerForm)
        {
            if (!ModelState.IsValid)
            {
                return View(registerForm);
            }
            else
            {
                _dbContext.Customers.Add(
                    new Customer
                    {
                        UserName = registerForm.UserName,
                        Email = registerForm.Email,
                        Password = registerForm.Password,
                        Role = Models.Enums.Role.user,
                        SavingGoal = 0,


                    }

                    );
                _dbContext.SaveChanges();

                var loginInfo = new LoginViewModel()
                {
                    userName = registerForm.UserName,
                    password = registerForm.Password,
                };
                var customer = Auth.IdentityValidation(loginInfo, _dbContext);   
                if (customer == null)
                {

                    return View(registerForm);
                }
                else
                {
                    Auth.Login(registerForm.Password, customer, this.HttpContext);
                    return RedirectToAction("Index", "Home");
                }
            }




        }


    }
}

FinanceTracker/Controllers/UserManagementController.cs
using FinanceTracker.Models;
using FinanceTracker.Models.Enums;
using FinanceTracker.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinanceTracker.Controllers
{
    [Authorize(Roles ="admin")]
    public class UserManagementController : Controller
    {
        private readonly ApplicationDbContext _dbContext;  

        public UserManagementController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext; 
        }
        public IActionResult Index()
        {
            List<Customer>? users = _dbContext.Customers.ToList();
            if (users == null) return View();
            else
            {
               var userList =  users.Select(user => new UserViewModel()
                {
                    UserName = user.UserName,
                    Email = user.Email,
                    Password = user.Password,
                    Role = Enum.GetName(typeof(Role), user.Role)!,
                    FirstName = user.FirstName??"N/A",
                    LastName = user.LastName?? "N/A",
                    CustomerId = user.CustomerId,   

                }).ToList()??new List<UserViewModel>();

            return View(userList);
            }
        }

        [HttpPost]
        public IActionResult Edit(UserViewModel userUpdateForm)
        {
            if (!ModelState.IsValid)
            {
                // Constructing an object with the error message
                var errorObject = new { error = "Invalid form" };

                // Returning the error object as JSON
                return Json(errorObject);
            }
            var userToEdit = _dbContext.Customers.Find(userUpdateForm.CustomerId);
            if (userToEdit == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                userToEdit.UserName = userUpdateForm.UserName;
                userToEdit.Email = userUpdateForm.Email;
                userToEdit.Password = userUpdateForm.Password;
                userToEdit.FirstName = userUpdateForm.FirstName;
                userToEdit.LastName = userUpdateForm.LastName;
                userToEdit.Role = (Role)Enum.Parse(typeof(Role), userUpdateForm.Role);


                _dbContext.SaveChanges();   
                return RedirectToAction("Index");
            }



        }
    }
}

FinanceTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanceTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/FinanceTracker.styles.css" asp-append-version="true" />

   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinanceTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Finance Overview</a>
                        </li>

                         @*<li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">Register</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FinanceManager" asp-action="Index">Finance Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="Index">User Management</a>
                        </li>
                        <li class="nav-item position-absolute end-0 ">
                            @if(User.Identity.IsAuthenticated){

                                <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            }else

                            {
                            
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinanceTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>